export const LOCALE_COOKIE_NAME = "freshbitan_locale";
export const locales = ["en", "bn"] as const;
export type SiteLocale = (typeof locales)[number];

export const isSiteLocale = (value: string | undefined | null): value is SiteLocale =>
  value === "en" || value === "bn";

export const defaultLocale: SiteLocale = "bn";

export const localeLabels: Record<SiteLocale, string> = {
  en: "English",
  bn: "বাংলা",
};

export const localeSeo = {
  en: {
    brandTitle: "FreshBitan | Premium Mangoes in Bangladesh",
    brandDescription:
      "Buy premium mangoes in Bangladesh from FreshBitan with orchard-first sourcing, mobile-friendly ordering, and delivery support.",
    keywords: [
      "FreshBitan",
      "buy mango online Bangladesh",
      "premium mango delivery Bangladesh",
      "Rajshahi mango online",
    ],
  },
  bn: {
    brandTitle: "FreshBitan | বাংলাদেশের প্রিমিয়াম আম",
    brandDescription:
      "FreshBitan থেকে বাংলাদেশের প্রিমিয়াম আম অর্ডার করুন। orchard-first sourcing, mobile-friendly ordering, এবং নির্ভরযোগ্য delivery support একসাথে পান।",
    keywords: [
      "FreshBitan",
      "বাংলাদেশে অনলাইনে আম কিনুন",
      "প্রিমিয়াম আম ডেলিভারি বাংলাদেশ",
      "রাজশাহীর আম অনলাইন",
    ],
  },
} as const;

export const dictionary = {
  en: {
    common: {
      home: "Home", products: "Products", about: "About", reviews: "Reviews", contact: "Contact", cart: "Cart", orderNow: "Order Now", featured: "Featured", details: "Details", whatsapp: "WhatsApp", facebook: "Facebook", quantity: "Quantity", checkout: "Checkout", remove: "Remove", clearCart: "Clear cart", browseProducts: "Browse products", viewCart: "View cart", submit: "Submit", product: "Product", name: "Name", phone: "Phone", email: "Email", address: "Address", district: "District", area: "Area", notes: "Notes", rating: "Rating", comment: "Comment", all: "All", orderSummary: "Order Summary", subtotal: "Subtotal", deliveryCharge: "Delivery Charge", total: "Total", checkoutLater: "Calculated at checkout", unit: "Unit", origin: "Origin", seasonalFruit: "Premium Mango", noEmail: "No email", productLink: "Product", loadingSubmit: "Submitting...", star: "Star",
    },
    nav: { tagline: "Premium Mangoes", toggleMenu: "Toggle menu" },
    footer: { explore: "Explore", contact: "Contact" },
    home: { metaTitle: "Home", metaDescription: "FreshBitan homepage for premium Bangladesh mango ordering across the season." },
    about: { metaTitle: "About", metaDescription: "Learn how FreshBitan sources, packages, and delivers premium mangoes across Bangladesh.", eyebrow: "About FreshBitan", title: "A mango brand built around freshness, trust, and simple ordering", approachTitle: "Our approach", approachBody: "FreshBitan is built for customers who want premium mangoes without guesswork. We keep the journey simple, mobile-friendly, and easy to trust from first click to final delivery update.", promiseTitle: "Our promise", seasonEyebrow: "Season Window", seasonTitle: "How the mango calendar shapes the FreshBitan experience", seasonDescription: "Different varieties arrive at different times, so we plan updates and communication around the real orchard season." },
    productsPage: { metaTitle: "Products", metaDescription: "Browse FreshBitan mango varieties with mobile-friendly filtering and ordering CTAs.", eyebrow: "FreshBitan Products", title: "Premium mangoes ready for inquiry or order", emptyTitle: "No products match this filter yet", emptyDescription: "Try another category or contact FreshBitan on WhatsApp for the latest mango availability.", emptyAction: "Contact us" },
    reviewsPage: { metaTitle: "Reviews", metaDescription: "Read customer feedback about FreshBitan mangoes and submit your own review.", heroEyebrow: "Customer Voice", heroTitle: "Real review moments from FreshBitan deliveries", listEyebrow: "Published Reviews", listTitle: "Trusted feedback from customers", listDescription: "The list below is powered by the backend reviews API.", emptyTitle: "No public reviews yet", emptyDescription: "Once reviews are approved by the team, they will appear here automatically.", emptyAction: "Contact FreshBitan", submitEyebrow: "Submit Review", submitTitle: "Share your experience after delivery", submitDescription: "Visitors can submit reviews directly from the public site. Reviews stay unpublished until approved." },
    contactPage: { metaTitle: "Contact", metaDescription: "Contact FreshBitan, start a WhatsApp lead, or place a quick public order through the website.", heroEyebrow: "Contact FreshBitan", heroTitle: "Turn interest into a confirmed order or WhatsApp lead", heroDescription: "Use the quick order form below, or reach out through WhatsApp and Facebook for product availability, delivery timing, or gifting support.", whatsappLead: "WhatsApp Lead", facebookPage: "Facebook Page", quickOrderEyebrow: "Quick Order", quickOrderTitle: "Place a direct order without a cart", quickOrderDescription: "This simple form posts to the backend public orders API and can redirect customers straight to an order success page.", noProductsTitle: "No orderable products published yet", noProductsDescription: "Publish at least one product in the backend to enable the quick order form.", noProductsAction: "Browse products", phoneLabel: "Phone", emailLabel: "Email", addressLabel: "Address" },
    cartPage: { metaTitle: "Cart", metaDescription: "Review your FreshBitan shopping cart, update quantities, and continue to checkout.", emptyTitle: "Your cart is still empty", emptyDescription: "Add your preferred mango packs to the cart, then continue to checkout.", emptyAction: "Browse products", helpTitle: "Need quick help?", helpDescription: "You can message us on WhatsApp for variety details, delivery information, or bulk orders.", helpAction: "WhatsApp support", heroBadge: "Shopping Cart", heroTitle: "Your selected FreshBitan products", heroDescription: "Update quantities, review a delivery estimate, and then continue to checkout.", summaryTitleSuffix: "item ready for checkout", summaryDescription: "Delivery charge will be calculated by district on the checkout page.", summaryFooterPrefix: "Delivery charge is estimated as", checkoutAction: "Proceed to checkout", addMoreAction: "Add more products", whatsappAction: "Discuss order on WhatsApp", lineTotal: "Line total", categoryFallback: "Premium Mango" },
    checkoutPage: { metaTitle: "Checkout", metaDescription: "Complete your FreshBitan order with delivery details and a mobile-friendly checkout form.", emptyTitle: "Add products to the cart before checkout", emptyDescription: "First add your preferred products to the cart, then return here to complete your order.", emptyAction: "Browse products", heroBadge: "Checkout", heroTitle: "Simple checkout, faster confirmation", heroDescription: "Use the correct phone number so the FreshBitan team can verify your order and confirm delivery timing.", customerName: "Your name", customerNamePlaceholder: "For example: Md. Rakib Hasan", phoneLabel: "Phone number", emailLabel: "Email (optional)", emailPlaceholder: "Optional", addressLabel: "Full address", addressPlaceholder: "House, road, village, post office, and full address", areaLabel: "Area / Police Station", areaPlaceholder: "For example: Uttara", districtLabel: "District", districtPlaceholder: "For example: Dhaka", paymentLabel: "Payment method", notesLabel: "Additional notes (optional)", notesPlaceholder: "For example: Evening delivery preferred", submit: "Confirm order", submitting: "Sending order...", whatsappSupport: "WhatsApp support", summaryTitle: "Your order total", summaryDescription: "This total includes delivery charge calculated automatically by district.", summaryFooterPrefix: "Delivery charge is usually", backToCart: "Back to cart", errName: "Please enter your name.", errPhone: "Please enter a valid phone number so we can contact you easily.", errAddress: "Please enter your full address.", errArea: "Please enter your area or police station.", errDistrict: "Please enter your district.", errSubmit: "Could not submit the order. Please try again." },
    orderSuccess: { metaTitle: "Order Success", metaDescription: "FreshBitan order confirmation page for successful order submissions.", badge: "Order received", title: "Thank you, your order has been submitted", description: "The FreshBitan team will review your order and contact you if needed.", browseAction: "See more products", contactAction: "Contact FreshBitan", refPrefix: "Your reference number is" },
    notFound: { title: "This page could not be found", description: "The page may have moved, or the product is no longer available. Let’s take you back to FreshBitan’s main collection.", homeAction: "Home", browseAction: "Browse products" },
  },
  bn: {
    common: { home: "হোম", products: "পণ্য", about: "আমাদের সম্পর্কে", reviews: "রিভিউ", contact: "যোগাযোগ", cart: "কার্ট", orderNow: "আজই অর্ডার করুন", featured: "ফিচার্ড", details: "বিস্তারিত", whatsapp: "WhatsApp", facebook: "Facebook", quantity: "পরিমাণ", checkout: "চেকআউট", remove: "Remove", clearCart: "কার্ট খালি করুন", browseProducts: "পণ্য দেখুন", viewCart: "কার্ট দেখুন", submit: "পাঠান", product: "পণ্য", name: "নাম", phone: "ফোন", email: "ইমেইল", address: "ঠিকানা", district: "জেলা", area: "এরিয়া", notes: "নোট", rating: "রেটিং", comment: "মন্তব্য", all: "সব", orderSummary: "অর্ডারের সারসংক্ষেপ", subtotal: "সাবটোটাল", deliveryCharge: "ডেলিভারি চার্জ", total: "মোট", checkoutLater: "চেকআউটে নির্ধারণ হবে", unit: "ইউনিট", origin: "উৎপত্তি", seasonalFruit: "প্রিমিয়াম আম", noEmail: "ইমেইল নেই", productLink: "পণ্য", loadingSubmit: "পাঠানো হচ্ছে...", star: "স্টার" },
    nav: { tagline: "প্রিমিয়াম আম", toggleMenu: "মেনু পরিবর্তন করুন" },
    footer: { explore: "এক্সপ্লোর", contact: "যোগাযোগ" },
    home: { metaTitle: "হোম", metaDescription: "বাংলাদেশজুড়ে FreshBitan-এর প্রিমিয়াম আম অর্ডারের হোমপেজ।" },
    about: { metaTitle: "আমাদের সম্পর্কে", metaDescription: "FreshBitan কীভাবে বাংলাদেশের জন্য প্রিমিয়াম আম সংগ্রহ, প্যাকেজ, এবং ডেলিভারি করে তা জানুন।", eyebrow: "FreshBitan সম্পর্কে", title: "তাজা আম, আস্থা, আর সহজ অর্ডারকে কেন্দ্র করে তৈরি একটি ব্র্যান্ড", approachTitle: "আমাদের কাজের ধরন", approachBody: "FreshBitan এমন ক্রেতাদের জন্য, যারা অনুমানের উপর না গিয়ে প্রিমিয়াম আম চান। আমরা প্রথম ক্লিক থেকে শেষ ডেলিভারি আপডেট পর্যন্ত পুরো অভিজ্ঞতাকে সহজ, মোবাইল-ফ্রেন্ডলি, আর আস্থাযোগ্য রাখি।", promiseTitle: "আমাদের প্রতিশ্রুতি", seasonEyebrow: "মৌসুমের সময়সূচি", seasonTitle: "আমের মৌসুম কীভাবে FreshBitan অভিজ্ঞতাকে গড়ে তোলে", seasonDescription: "ভিন্ন ভিন্ন জাত ভিন্ন সময়ে আসে, তাই আমরা বাস্তব orchard season অনুযায়ী আপডেট এবং যোগাযোগ পরিকল্পনা করি।" },
    productsPage: { metaTitle: "পণ্য", metaDescription: "FreshBitan-এর আম দেখুন, filter করুন, এবং সহজে অর্ডার শুরু করুন।", eyebrow: "FreshBitan পণ্য", title: "ইনকোয়ারি বা অর্ডারের জন্য প্রস্তুত প্রিমিয়াম আম", emptyTitle: "এই ফিল্টারে এখনো কোনো পণ্য নেই", emptyDescription: "অন্য category চেষ্টা করুন অথবা সর্বশেষ আমের availability জানতে WhatsApp-এ যোগাযোগ করুন।", emptyAction: "যোগাযোগ করুন" },
    reviewsPage: { metaTitle: "রিভিউ", metaDescription: "FreshBitan-এর আম সম্পর্কে গ্রাহকের মতামত পড়ুন এবং নিজের রিভিউ দিন।", heroEyebrow: "গ্রাহকের কথা", heroTitle: "FreshBitan ডেলিভারি থেকে পাওয়া বাস্তব রিভিউ", listEyebrow: "প্রকাশিত রিভিউ", listTitle: "বিশ্বস্ত গ্রাহক মতামত", listDescription: "নিচের তালিকাটি backend reviews API থেকে আনা হয়েছে।", emptyTitle: "এখনো কোনো public review নেই", emptyDescription: "টিম approve করলে রিভিউ এখানে স্বয়ংক্রিয়ভাবে দেখানো হবে।", emptyAction: "FreshBitan-এর সাথে যোগাযোগ", submitEyebrow: "রিভিউ দিন", submitTitle: "ডেলিভারির পর আপনার অভিজ্ঞতা শেয়ার করুন", submitDescription: "পাবলিক সাইট থেকেই রিভিউ পাঠানো যায়। approve না হওয়া পর্যন্ত রিভিউ প্রকাশিত হবে না।" },
    contactPage: { metaTitle: "যোগাযোগ", metaDescription: "FreshBitan-এর সাথে যোগাযোগ করুন, WhatsApp lead শুরু করুন, বা ওয়েবসাইট থেকেই quick order দিন।", heroEyebrow: "FreshBitan-এর সাথে যোগাযোগ", heroTitle: "আগ্রহকে confirmed order বা WhatsApp lead-এ পরিণত করুন", heroDescription: "নিচের quick order form ব্যবহার করুন, অথবা product availability, delivery timing, বা gifting support-এর জন্য WhatsApp ও Facebook-এ যোগাযোগ করুন।", whatsappLead: "WhatsApp লিড", facebookPage: "Facebook পেজ", quickOrderEyebrow: "কুইক অর্ডার", quickOrderTitle: "কার্ট ছাড়াই সরাসরি অর্ডার দিন", quickOrderDescription: "এই ফর্মটি backend public orders API-তে পোস্ট করে এবং সফল হলে order success page-এ নিয়ে যেতে পারে।", noProductsTitle: "অর্ডারযোগ্য কোনো পণ্য এখনো প্রকাশিত হয়নি", noProductsDescription: "Quick order form চালু করতে backend-এ অন্তত একটি পণ্য publish করুন।", noProductsAction: "পণ্য দেখুন", phoneLabel: "ফোন", emailLabel: "ইমেইল", addressLabel: "ঠিকানা" },
    cartPage: { metaTitle: "কার্ট", metaDescription: "FreshBitan কার্ট দেখুন, quantity আপডেট করুন, এবং checkout-এ এগিয়ে যান।", emptyTitle: "আপনার কার্ট এখনো খালি", emptyDescription: "পছন্দের আমের প্যাক বেছে কার্টে যোগ করুন, তারপর checkout করে অর্ডার কনফার্ম করুন।", emptyAction: "পণ্য দেখুন", helpTitle: "দ্রুত সাহায্য দরকার?", helpDescription: "চাইলে WhatsApp-এ message করে variety, delivery, বা bulk order নিয়ে কথা বলতে পারেন।", helpAction: "WhatsApp সহায়তা", heroBadge: "Shopping Cart", heroTitle: "আপনার নির্বাচিত FreshBitan পণ্য", heroDescription: "Quantity আপডেট করুন, delivery মোটামুটি হিসাব দেখুন, তারপর checkout-এ গিয়ে অর্ডার সম্পন্ন করুন।", summaryTitleSuffix: "টি আইটেম checkout-এর জন্য প্রস্তুত", summaryDescription: "Delivery charge checkout page-এ district অনুযায়ী হিসাব হবে।", summaryFooterPrefix: "ডেলিভারি চার্জ ধরা হয়েছে", checkoutAction: "Checkout করুন", addMoreAction: "আরও পণ্য যোগ করুন", whatsappAction: "WhatsApp-এ অর্ডার আলোচনা", lineTotal: "লাইন টোটাল", categoryFallback: "প্রিমিয়াম আম" },
    checkoutPage: { metaTitle: "চেকআউট", metaDescription: "ডেলিভারি তথ্য দিয়ে FreshBitan অর্ডার সম্পন্ন করুন।", emptyTitle: "Checkout করার আগে কার্টে পণ্য যোগ করুন", emptyDescription: "প্রথমে আপনার পছন্দের পণ্য কার্টে যোগ করুন, তারপর এখান থেকে delivery details দিয়ে অর্ডার সম্পন্ন করুন।", emptyAction: "পণ্য দেখুন", heroBadge: "Checkout", heroTitle: "সহজ checkout, দ্রুত কনফার্মেশন", heroDescription: "ফোন নম্বরটি ঠিকভাবে দিন। FreshBitan team order verify করে delivery timing ও payment support জানিয়ে দেবে।", customerName: "আপনার নাম", customerNamePlaceholder: "যেমন: মো. রাকিব হাসান", phoneLabel: "ফোন নম্বর", emailLabel: "ইমেইল (ঐচ্ছিক)", emailPlaceholder: "Optional", addressLabel: "পূর্ণ ঠিকানা", addressPlaceholder: "বাড়ি/রোড/গ্রাম/পোস্ট অফিসসহ পূর্ণ ঠিকানা লিখুন", areaLabel: "এরিয়া / থানা", areaPlaceholder: "যেমন: উত্তরা", districtLabel: "জেলা", districtPlaceholder: "যেমন: ঢাকা", paymentLabel: "পেমেন্ট পদ্ধতি", notesLabel: "অতিরিক্ত নোট (ঐচ্ছিক)", notesPlaceholder: "যেমন: বিকেলে ডেলিভারি হলে ভালো হয়", submit: "অর্ডার কনফার্ম করুন", submitting: "অর্ডার পাঠানো হচ্ছে...", whatsappSupport: "WhatsApp সহায়তা", summaryTitle: "আপনার অর্ডারের হিসাব", summaryDescription: "এই মোট টাকার মধ্যে delivery charge district অনুযায়ী automatically ধরা হয়েছে।", summaryFooterPrefix: "ডেলিভারি চার্জ সাধারণত", backToCart: "কার্টে ফিরে যান", errName: "আপনার নাম লিখুন।", errPhone: "সঠিক ফোন নম্বর লিখুন, যাতে আমরা সহজে যোগাযোগ করতে পারি।", errAddress: "পূর্ণ ঠিকানা লিখুন।", errArea: "এরিয়া বা থানা লিখুন।", errDistrict: "জেলা লিখুন।", errSubmit: "অর্ডার পাঠানো যায়নি। কিছুক্ষণ পর আবার চেষ্টা করুন।" },
    orderSuccess: { metaTitle: "অর্ডার সফল", metaDescription: "সফল অর্ডার সাবমিশনের জন্য FreshBitan order confirmation page।", badge: "Order received", title: "ধন্যবাদ, আপনার অর্ডার জমা হয়েছে", description: "FreshBitan team আপনার order review করবে এবং প্রয়োজনে যোগাযোগ করবে।", browseAction: "আরো পণ্য দেখুন", contactAction: "FreshBitan-এর সাথে যোগাযোগ", refPrefix: "আপনার reference number হলো" },
    notFound: { title: "এই পাতাটি পাওয়া যায়নি", description: "এই পেজটি হয়তো সরানো হয়েছে, অথবা পণ্যটি আর পাওয়া যাচ্ছে না। চলুন FreshBitan-এর মূল collection-এ ফিরে যাই।", homeAction: "হোম", browseAction: "পণ্য দেখুন" },
  },
} as const;

export const getDictionary = (locale: SiteLocale) => dictionary[locale];
